CREATE TABLE book
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title          VARCHAR(255),
    author         VARCHAR(255),
    genre          VARCHAR(255),
    published_date date,
    CONSTRAINT pk_book PRIMARY KEY (id)
);